version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  devops-project:
    container_name: devops-project
    image: mohamedsrh/devops-project:latest
    ports:
      - 8086:8086
    depends_on:
      - mysql
      - prometheus

  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter:latest
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: "root:@(mysql:3306)/"
    depends_on:
      - mysql
      - prometheus

  angular-app:
    container_name: angular-app
    image: mohamedsrh/angular-app:latest
    ports:
      - 8084:80
volumes:
  mysql_data: {}
  prometheus_data: {}
  grafana_data: {}