version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    depends_on:
      - prometheus

  devops-project:
    container_name: devops-project
    image: mohamedsrh/devops-project:latest
    ports:
      - 8086:8086
    depends_on:
      - mysql
      - prometheus
  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter:latest
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: "root:root@(mysql:3306)/"
    depends_on:
      - mysql
      - prometheus

volumes:
  mysql_data: {}
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}