scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.28.121.188:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['172.28.121.188:8086']
        labels:
          group: 'production'

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['172.28.121.188:9104']